### ISSUE TITLE
jig for flashing

### ISSUE THREAD

**Issue by Lavaerius** [sycophantic/wyze_bulb#1]
What kind of jig did you use to get the flash off this?  I've attempted to insert some headers with leads solder on, but I don't think that's working.

I'm expecting that with 3v3 and ground connected I'd see the SSID spring to life, but maybe I'm missing something, do I have to pull something up to see that?

Even without that, I'm trying to run an esptool flash_delete or whatever against it, and am just timing out.  I've grounded the wre pin to ground as suggested.  I'd take whatever suggestions you've got.

Thanks.

**Comment by sycophantic** [comment]
I took jumper wires and bent the pins so I could hook the pins, see picture below. I used the RF shield as ground. Hope this helps.

![image](https://user-images.githubusercontent.com/634076/81612972-a713ba00-93ab-11ea-8041-96f1422db236.png)

**Comment by Lavaerius** [comment]
did you power on with WRE grounded to enter flash_mode?
I have an external power supply, and shared ground.  I've got the alligator clip on the shielding, and connecting all ground locations into a bread board.

I'm trying to connect from the uart pins of a pi zero w, and this thing is just a brick staring back at me. running esptool erase_flash.

**Comment by sycophantic** [comment]
Yes. I powered on with the WRE pin grounded. Also, make sure you are using the latest esptool. I had issues with older versions. Are you sure your connections to the pi are correct and the pi config is right for using the uart?

**Comment by Lavaerius** [comment]
All references to console connections are removed, and uart enabled is done. Tx-rx and vice versa..

When the wre was not grounded, did the wifi come online, and you saw the wyze ssid?

**Comment by sycophantic** [comment]
The wifi came on when WRE was not grounded. Try just running esptool device_info, it should try to connect a few times so you can mess around with powering it up and down and see if you can get it to communicate.

**Comment by Lavaerius** [comment]
Encouraging.  I can measure a 125mA draw when wre is not to ground, and 60 mA draw when it is.  I'm wagering that's the difference between turning on the radio or not.  And leads me to believe power is getting through.  I still can't see the SSID now when not grounded which is weird to me.

I'm wondering now if there is an issue with the PI's serial config.  On the surface it looks good, but obviously I'm not getting anything.  

I also am unable to run device_info from esptool.py, that doesn't seem to be a valid command according to the readme.  I'm on version 2.8

Thinking about using a separate device coming off of my windows desktop with some logic level converters to remove the pi from the equation.

Still confused over the lack of ssid though....

Sigh, this was mostly just thinking out loud.  Thanks for being responsive.

**Comment by sycophantic** [comment]
Any luck? The command is actually chip_id. I use it to make sure I can communicate with the device. I'd suggest getting a USB to TTL adapter with jumpers to adjust for 5v or 3.3v logic levels.

**Comment by Lavaerius** [comment]
No, not yet.
I'm thinking of tearing down another bulb (I bought a three pack for a project) and checking if the voltage on 3v3 and ground bring up the wifi there.

**Comment by Lavaerius** [comment]
All right!

turns out I had been too cautious with the power running to the module.  spec clearly states 2.7-3.6 operating voltage, so I had been attempting various things like voltage dividers, and diodes etc.  As I didn't have a good 3v3 power supply.  got frustrated and just fed it 3AA batteries in series....

It was a little high on voltage, but I got all three flashed.

Thanks for the sounding board on this...man was that frustrating!

**Comment by sycophantic** [comment]
Awesome!
