### ISSUE TITLE
warmth not allowing bulb to turn off completely

### ISSUE THREAD

**Issue by Lavaerius** [sycophantic/wyze_bulb#2]
Hey, it's me again.  I'm also asking in the discord, but this bulb seems like no one is using, so I'm also gonna poke you too.

Did you have any trouble getting the warmth bulbs to turn off completely when configured with your template?  the only way I can get the bulb as a whole to turn off all the way is to remove gpio 14 functionality.

I've attempted to set several options to de-couple the PWM from each other, but it doesn't affect off state not truly being off.

I'm hoping that it's not something goofy, like having fed the chip a bit of extra power to get it to talk fried something, that would be a shame.

**Comment by sycophantic** [comment]
I noticed mine are very dim when off too. I haven't had a chance to figure out why.

**Comment by Lavaerius** [comment]
well, it's good to know then we're at least in that same boat.

If you don't care about warmth, turning off gpio14 does the trick.  If i find out anything I'll let you know.

**Comment by Lavaerius** [comment]
Someone did the work for us!
https://templates.blakadder.com/wyze_WLPA19.html

I've tested with a couple of bulbs on most recent firmware, and I've got the ability to adjust warmth and brightness now.

on that page is also a link to an OTA firmware flasher for the devices that I've not tested yet.
